### ISSUE TITLE
Port to opencv3

### ISSUE THREAD

**Issue by pranitbauva1997** [Swarm-IITKgp/2d-image-stitching#1]
This code works fine in opencv2. Although there are much more features in opencv3 especially for 3D reconstruction, and thus it would be great if we can port all of our code to opencv3. I think for this code, only the ORB descriptor part changes. I will send a PR for this by evening.

**Comment by surya2191997** [comment]
Ok fine. Should I also extend this to >2 images ? It can be done by just applying this procedure iteratively.

**Comment by pranitbauva1997** [comment]
Now I think we can directly focus on the video. Wait till we clean up other issues and then we can write this part. I think #7 (Make the code modular) would be required before proceeding to the videos part.

**Comment by SpandanKumarSahu** [comment]
Great work @surya2191997! 
I can't wait to run this on my laptop, but the results on test data are amazing.
If we can make it modular, then we can recursively  stitch multiple images or videos as required.
